### ISSUE TITLE
Auth gating should be in the beforeModel hook

### ISSUE THREAD

**Issue by NullVoxPopuli** [PorterK/wedding#1]
idk if you want me to poke at your code or not 🤷 

Typically,
 - beforeModel - gating access
 - model - loading minimally required data to view the page (sometimes this is totally omitted, and data is loaded from components)
 - afterModel - any further validations that might require the model data

https://github.com/PorterK/wedding/blob/39255e58d596a624c3a8c9ccf4a90049d2cd6974/app/routes/admin.js#L12

```ts
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default class AdminRoute extends Route {
  @service('session') session

  async beforeModel() {
    try {
      await this.session.fetch();
    } catch {}

    if (!this.session.isAuthenticated) {
      this.transitionTo('login');
    }
  }
}
```

**Comment by PorterK** [comment]
Thank you! Feel free to poke along
